# Udemy - Deep Learning A-Z: Hands-on Python & R in Data Science

Artificial Neural Networks - Classification

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

**1) Data Preprocessing**

In [28]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [29]:
X = df.iloc[:,4:-1].values # array
y = df.iloc[:,-1].values # array

X_df = df.iloc[:,4:-1]
y_df = df.iloc[:,-1]

In [30]:
# a) Missinig values
df.info()

# No NaNs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [31]:
X_df.head()

Geography  Gender  Age  ...  HasCrCard  IsActiveMember  EstimatedSalary
0    France  Female   42  ...          1               1        101348.88
1     Spain  Female   41  ...          0               1        112542.58
2    France  Female   42  ...          1               0        113931.57
3    France  Female   39  ...          0               0         93826.63
4     Spain  Female   43  ...          1               1         79084.10

[5 rows x 9 columns]

In [33]:
# b) Encoding categorical features

# Label encoding "Gender"
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

X

array([['France', 0, 24, ..., 1, 1, 101348.88],
       ['Spain', 0, 23, ..., 0, 1, 112542.58],
       ['France', 0, 24, ..., 1, 0, 113931.57],
       ...,
       ['France', 0, 18, ..., 0, 1, 42085.58],
       ['Germany', 1, 24, ..., 1, 0, 92888.52],
       ['France', 0, 10, ..., 1, 0, 38190.78]], dtype=object)

In [34]:
# One-Hot-Encoding "Geography"

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(),[0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [35]:
X[1]

array([0.0, 0.0, 1.0, 0, 23, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [37]:
# c) Splitting dataset into the training and test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [38]:
# d) Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**2) Building an ANN**

a) Initializing the ANN

In [41]:
ann = tf.keras.models.Sequential()

b) Adding the input layer and the first hidden layer

In [42]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # units = 6 -> number of hidden neurons

c) Adding the second hidden layer

In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

d) Adding the output layer

In [44]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**3) Training the ANN**

a) Compiling the ANN

In [45]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) # not binary problem: categorical_crossentropy and activation function = softmax

b) Training the ANN on the training set

In [46]:
ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5574 - accuracy: 0.7850
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4739 - accuracy: 0.7989
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4517 - accuracy: 0.7996
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4414 - accuracy: 0.7938
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4283 - accuracy: 0.8073
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4181 - accuracy: 0.8116
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4139 - accuracy: 0.8221
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4027 - accuracy: 0.8302
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8376
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3873 - accura

4) Making the prediction and evaluating the model

a) Predicting the result of a single observation

In [47]:
# Without "Credit score"!
ann.predict(sc.transform([[1.0, 1.0, 1.0, 1, 40, 3, 60000, 2, 1, 1, 50000]])) # Always in: [[]]-> 2D array

array([[0.09660661]], dtype=float32)

In [49]:
ann.predict(sc.transform([[1.0, 1.0, 1.0, 1, 40, 3, 60000, 2, 1, 1, 50000]])) >0.5

array([[False]])

b) Predicting the test set results

In [65]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_compare = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1)
y_compare

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

c) Making the Confusion Matrix

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   62]
 [ 212  203]]


0.863